**EXPLORATORY DATA ANALYSIS**

Understanding the dataset to explore how the data is present in the database and if there is a need of creating some aggregated tables that can help with

. Vendor selection for profitability
. Product Pricing Optimization

In [2]:
import pandas as pd 
import sqlite3

In [3]:
# creating database connection 
conn = sqlite3.connect('inventorys.db')

In [6]:
# Checking tables present in the database
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
print(tables)

                   name
0       begin_inventory
1         end_inventory
2             purchases
3       purchase_prices
4                 sales
5        vendor_invoice
6  vendor_sales_summary

In [9]:
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('Count of records :' , pd.read_sql(f"select count(*) as count from {table}",conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5",conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records : 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records : 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records : 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records : 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records : 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records : 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
Count of records : 32076

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,StockPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897


. The purchases table contains actual purchase data, including the date of purchase, products (brands) purchased by vendors, the amount paid (in dollars), and the quantity purchased.  

. The purchase price column is derived from the purchase_prices table, which provides product-wise actual and purchase prices. The combination of vendor and brand is unique in this table.  

. The vendor_invoice table aggregates data from the purchases table, summarizing quantity and dollar amounts, along with an additional column for freight. This table maintains uniqueness based on vendor and PO number.  

. The sales table captures actual sales transactions, detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned.  

As the data that we need for analysis is distributed in different tables, we need to create a summary table containing:  
- purchase transactions made by vendors  
- sales transaction data  
- freight costs for each vendor  
- actual product prices from vendors

In [11]:

vendor_invoice = pd.read_sql_query("SELECT * FROM vendor_invoice", conn)
print(vendor_invoice.columns)

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [12]:
freight_summary = pd.read_sql_query("""select VendorNumber , SUM(Freight) as FreightCost from Vendor_invoice
Group By VendorNumber""",conn)
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [13]:

pd.read_sql_query("""
SELECT
    P.VendorNumber, 
    P.VendorName, 
    P.Brand,
    P.PurchasePrice,         -- correct column from Purchases
    pp.Volume,
    pp.Price AS ActualPrice,
    SUM(P.Quantity) AS TotalPurchaseQuantity,
    SUM(P.Dollars) AS TotalPurchaseDollars
FROM purchases AS P
JOIN purchase_prices AS pp
    ON P.Brand = pp.Brand
Where P.PurchasePrice > 0
GROUP BY P.VendorNumber, P.VendorName, P.Brand
ORDER BY TotalPurchaseDollars
""", conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [14]:
pd.read_sql_query(""" SELECT 
   vendorNo,
   Brand,
   SUM(SalesDollars) as TotalSalesDollars,
   SUM(SalesPrice) as TotalSalesPrice,
   SUM(SalesPrice) as TotalSalesQuantity,
   SUM(ExciseTax) asTotalExciseTax
   From Sales
   Group by VendorNo, Brand
   Order by TotalSalesDollars""",conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,asTotalExciseTax
0,8004,5287,0.98,0.98,0.98,0.10
1,9206,2773,0.99,0.99,0.99,0.05
2,3252,3933,1.98,0.99,0.99,0.10
3,3924,9123,1.98,0.99,0.99,0.10
4,10050,3623,1.98,1.98,1.98,0.10
...,...,...,...,...,...,...
11267,3960,3545,4223107.62,545778.28,545778.28,249587.83
11268,3960,4261,4475972.88,420050.01,420050.01,368242.80
11269,17035,8068,4538120.60,461140.15,461140.15,343854.07
11270,4425,3405,4819073.49,561512.37,561512.37,294438.66
11271,1128,1233,5101919.51,672819.31,672819.31,260999.20

In [15]:

# This code is use for the extracting data but this take a lot of time to run the query and show operational error.

# import time 
# start = time.time()
# final_table = pd.read_sql_query(""" SELECT
#     pp.VendorNumber,
#     pp.Brand,
#     pp.Price as ActualPrice,
#     pp.PurchasePrice,
#     SUM(s.SalesQuantity) as TotalSalesQuantity,
#     SUM(s.SalesDollars) as TotalSalesDollars,
#     SUM(s.SalesPrice) as TotalSalesPrice,
#     SUM(s.ExciseTax) as TotalExciseTax,
#     SUM(vi.Quantity) as TotalPurchaseQuantity,
#     SUM(vi.Dollars) as TotalPurchaseDollars,
#     SUM(vi.Freight) as TotalFreightCost
# From purchase_prices pp
# JOIN sales s
#      ON pp.VendorNumber = s.VendorNo
#      AND pp.Brand = s.Brand 
# JOIN Vendor_invoice  vi
#      ON pp.VendorNumber = vi.VendorNumber
#      Group by pp.VendorNumber , pp.Brand , pp.Price , pp.PurchasePrice""",conn)
    
# end = time.time()

In [16]:
# This code is optimised form of sql for extracting data from conn it runs in short period of time 
import time
start=time.time()
vendor_sales_summary = pd.read_sql_query("""WITH FreightSummary As(
    Select
        VendorNumber,
        SUM(Freight) AS FreightCost
    From vendor_invoice
    Group by VendorNumber),

    
PurchaseSummary AS (
    SELECT 
        P.VendorNumber, 
        P.VendorName,
        P.Brand,
        P.Description,
        P.PurchasePrice,
        pp.Price As ActualPrice,
        pp.Volume,
        SUM(P.Quantity) AS TotalPurchaseQuantity,
        SUM(P.Dollars) AS TotalPurchaseDollars
    From purchases P
    JOIN purchase_prices pp
         ON P.Brand = pp.Brand
    Where P.PurchasePrice > 0 
    Group BY P.VendorNumber , P.VendorName , P.Brand , P.Description , P.PurchasePrice , pp.Price , pp.Volume),

SalesSummary AS (
    SELECT
       VendorNo,
       Brand,
       SUM(SalesQuantity) AS TotalSalesQuantity,
       SUM(SalesDollars) AS TotalSalesDollars,
       SUM(SalesPrice) AS TotalSalesPrice,
       Sum(ExciseTax) AS TotalExciseTax
    FROM sales
    Group by VendorNo, Brand)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost
From PurchaseSummary ps
LEFT JOIN SalesSummary ss
     ON ps.VendorNumber = ss.VendorNo
     AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary fs
     ON ps.VendorNumber = fs.VendorNumber
ORDER BY ps.TotalpurchaseDollars DESC """,conn) 
end = time.time()

In [17]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64,5.0,15.95,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34,134.0,65.66,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2,1.48,2.0,1.98,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1,1.47,72.0,143.28,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71,86.0,85.14,33.66,4.46,38994.78

This Query generates a vendor_wise sales and purchase summary , which is valuable for:

#***Performance Optimization:***

 1)The query involves heavy join and aggregations on large dataset like sales and purchase.
 
 2)Storing the pre-aggregated results avoids repeated expensive computations .
 
 3)Helps in analyzing sales, Purchase , and pricing for different vendors and brands .
 
 4)Future Benefits of Storing this data for faster Dashboarding and Reporting .
 
 5)Instead of running expensive queries each time , dashboards can fetch data quickly from vendor_sales_summary.

In [19]:
vendor_sales_summary.dtypes  # just for checking

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                    object
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [20]:
vendor_sales_summary.isnull().sum()  # here are some values which are missing because vendor purchase the product but there are not sale
                                     # Just for checking

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [21]:
vendor_sales_summary.head()   # just for checking

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07

In [22]:
vendor_sales_summary['VendorName'].unique()    # just for checking

array(['BROWN-FORMAN CORP          ', 'MARTIGNETTI COMPANIES',
       'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ',
       'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
       'MAJESTIC FINE WINES        ', 'ULTRA BEVERAGE COMPANY LLP ',
       'STOLI GROUP,(USA) LLC      ', 'PROXIMO SPIRITS INC.       ',
       'MOET HENNESSY USA INC      ', 'CAMPARI AMERICA            ',
       'SAZERAC CO INC             ', 'CONSTELLATION BRANDS INC   ',
       'M S WALKER INC             ', 'SAZERAC NORTH AMERICA INC. ',
       'PALM BAY INTERNATIONAL INC ', 'REMY COINTREAU USA INC     ',
       'SIDNEY FRANK IMPORTING CO  ', 'E & J GALLO WINERY         ',
       'WILLIAM GRANT & SONS INC   ', 'HEAVEN HILL DISTILLERIES   ',
       'DISARONNO INTERNATIONAL LLC', 'EDRINGTON AMERICAS         ',
       'CASTLE BRANDS CORP.        ', 'SOUTHERN WINE & SPIRITS NE ',
       'STE MICHELLE WINE ESTATES  ', 'TRINCHERO FAMILY ESTATES   ',
       'MHW LTD                    ', 'WINE GROUP INC             ',
       'PERFECTA WINES             ', 'LUXCO INC                  ',
       'TREASURY WINE ESTATES      ', 'DIAGEO CHATEAU ESTATE WINES',
       'SHAW ROSS INT L IMP LTD    ', 'PINE STATE TRADING CO      ',
       'PHILLIPS PRODUCTS CO.      ', 'CALEDONIA SPIRITS INC      ',
       'STATE WINE & SPIRITS   ', 'KOBRAND CORPORATION        ',
       'BANFI PRODUCTS CORP        ', 'VINEYARD BRANDS INC        ',
       'DELICATO VINEYARDS INC     ', 'FABRIZIA SPIRITS LLC       ',
       'DUGGANS DISTILLED PRODUCTS ', 'Serralles Usa LLC          ',
       'SEA HAGG DISTILLERY LLC    ', 'OLE SMOKY DISTILLERY LLC   ',
       'VRANKEN AMERICA            ', 'KLIN SPIRITS LLC           ',
       'LAIRD & CO                 ', 'ADAMBA IMPORTS INTL INC    ',
       'LATITUDE BEVERAGE COMPANY  ', 'FREDERICK WILDMAN & SONS   ',
       'MCCORMICK DISTILLING CO    ', 'CHARLES JACQUIN ET CIE INC ',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY           ',
       'AMERICAN VINTAGE BEVERAGE  ', 'MANGO BOTTLING INC         ',
       'SWEET BABY VINEYARD        ', 'NICHE W & S                ',
       'LABELLE VYDS AND WINERY    ', 'FLAG HILL WINERY & VINEYARD',
       'SMOKY QUARTZ DISTILLERY LLC', 'PREMIUM PORT WINES, INC.   ',
       'Russian Standard Vodka     ', 'Dunn Wine Brokers          ',
       'WEIN BAUER INC             ', 'BULLY BOY DISTILLERS       ',
       'ATLANTIC IMPORTING COMPANY ', 'PREMIER DISTRIBUTORS       ',
       'VINILANDIA USA             ', 'PARK STREET IMPORTS LLC    ',
       'TAKARA SAKE USA INC        ', 'SEA BREEZE CELLARS LLC     ',
       'STARK BREWING COMPANY      ', 'TY KU LLC                  ',
       'PSP WINES ', 'TAMWORTH DISTILLING        ',
       'ZORVINO VINEYARDS          ', 'SOUTHERN GLAZERS W&S OF NE ',
       'HOOD RIVER DISTILLERS, Inc.', 'CRUSH WINES                ',
       'POVERTY LANE ORCHARDS      ', 'DJINN SPIRITS LLC          ',
       'MOONLIGHT MEADERY          ', 'TALL SHIP DISTILLERY LLC   ',
       'FORTUNE WINE BROKERS LLC   ', 'BLACK COVE BEVERAGES       ',
       'VINEXTRA INC               ', 'SURVILLE ENTERPRISES CORP  ',
       'JEWELL TOWNE VINEYARDS     ', 'SWEETWATER FARM         ',
       'MARTIGNETTI COMPANIES ', 'ALTAMAR BRANDS LLC         ',
       'CANDIA VINEYARDS           ', 'INCREDIBREW INC            ',
       'ALISA CARR BEVERAGES           ', 'STELLAR IMPORTING CO LLC   ',
       'FULCHINO VINEYARD INC      ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'Circa Wines                ', 'VINEDREA WINES LLC         ',
       'BLACK PRINCE DISTILLERY INC', 'VINEYARD BRANDS LLC        ',
       'THE IMPORTED GRAPE LLC     ', 'WALPOLE MTN VIEW WINERY    ',
       'GILMANTON WINERY & VINEYARD', 'HAUNTING WHISPER VYDS      ',
       'STAR INDUSTRIES INC.       ', 'LOYAL DOG WINERY           ',
       'R.P.IMPORTS INC            ', 'THE PIERPONT GROUP LLC     ',
       'APPOLO VINEYARDS LLC       ', 'BLACK ROCK SPIRITS LLC     ',
       'CENTEUR IMPORTS LLC        ', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE  ', 'UNCORKED       ',
       'BRONCO WINE COMPANY        ', 'MILTONS DISTRIBUTING CO    ',
       'TRUETT HURST               ', 'LAUREATE IMPORTS CO        ',
       'FANTASY FINE WINES CORP    ', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS     ', 'CAPSTONE INTERNATIONAL     ',
       'FLAVOR ESSENCE INC         '], dtype=object)

In [23]:
vendor_sales_summary['Description'].unique()         # just for checking

array(['Jack Daniels No 7 Black', "Tito's Handmade Vodka",
       'Absolut 80 Proof', ..., 'Crown Royal Apple',
       'Concannon Glen Ellen Wh Zin', 'The Club Strawbry Margarita'],
      dtype=object)

In [24]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')

In [25]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                   float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [26]:
vendor_sales_summary.fillna(0,inplace=True)

In [27]:
vendor_sales_summary.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesDollars        0
TotalSalesPrice          0
TotalExciseTax           0
FreightCost              0
dtype: int64

In [28]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [29]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP', 'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA',
       'DIAGEO NORTH AMERICA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'MAJESTIC FINE WINES',
       'ULTRA BEVERAGE COMPANY LLP', 'STOLI GROUP,(USA) LLC',
       'PROXIMO SPIRITS INC.', 'MOET HENNESSY USA INC', 'CAMPARI AMERICA',
       'SAZERAC CO INC', 'CONSTELLATION BRANDS INC', 'M S WALKER INC',
       'SAZERAC NORTH AMERICA INC.', 'PALM BAY INTERNATIONAL INC',
       'REMY COINTREAU USA INC', 'SIDNEY FRANK IMPORTING CO',
       'E & J GALLO WINERY', 'WILLIAM GRANT & SONS INC',
       'HEAVEN HILL DISTILLERIES', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS', 'CASTLE BRANDS CORP.',
       'SOUTHERN WINE & SPIRITS NE', 'STE MICHELLE WINE ESTATES',
       'TRINCHERO FAMILY ESTATES', 'MHW LTD', 'WINE GROUP INC',
       'PERFECTA WINES', 'LUXCO INC', 'TREASURY WINE ESTATES',
       'DIAGEO CHATEAU ESTATE WINES', 'SHAW ROSS INT L IMP LTD',
       'PINE STATE TRADING CO', 'PHILLIPS PRODUCTS CO.',
       'CALEDONIA SPIRITS INC', 'STATE WINE & SPIRITS',
       'KOBRAND CORPORATION', 'BANFI PRODUCTS CORP',
       'VINEYARD BRANDS INC', 'DELICATO VINEYARDS INC',
       'FABRIZIA SPIRITS LLC', 'DUGGANS DISTILLED PRODUCTS',
       'Serralles Usa LLC', 'SEA HAGG DISTILLERY LLC',
       'OLE SMOKY DISTILLERY LLC', 'VRANKEN AMERICA', 'KLIN SPIRITS LLC',
       'LAIRD & CO', 'ADAMBA IMPORTS INTL INC',
       'LATITUDE BEVERAGE COMPANY', 'FREDERICK WILDMAN & SONS',
       'MCCORMICK DISTILLING CO', 'CHARLES JACQUIN ET CIE INC',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY',
       'AMERICAN VINTAGE BEVERAGE', 'MANGO BOTTLING INC',
       'SWEET BABY VINEYARD', 'NICHE W & S', 'LABELLE VYDS AND WINERY',
       'FLAG HILL WINERY & VINEYARD', 'SMOKY QUARTZ DISTILLERY LLC',
       'PREMIUM PORT WINES, INC.', 'Russian Standard Vodka',
       'Dunn Wine Brokers', 'WEIN BAUER INC', 'BULLY BOY DISTILLERS',
       'ATLANTIC IMPORTING COMPANY', 'PREMIER DISTRIBUTORS',
       'VINILANDIA USA', 'PARK STREET IMPORTS LLC', 'TAKARA SAKE USA INC',
       'SEA BREEZE CELLARS LLC', 'STARK BREWING COMPANY', 'TY KU LLC',
       'PSP WINES', 'TAMWORTH DISTILLING', 'ZORVINO VINEYARDS',
       'SOUTHERN GLAZERS W&S OF NE', 'HOOD RIVER DISTILLERS, Inc.',
       'CRUSH WINES', 'POVERTY LANE ORCHARDS', 'DJINN SPIRITS LLC',
       'MOONLIGHT MEADERY', 'TALL SHIP DISTILLERY LLC',
       'FORTUNE WINE BROKERS LLC', 'BLACK COVE BEVERAGES', 'VINEXTRA INC',
       'SURVILLE ENTERPRISES CORP', 'JEWELL TOWNE VINEYARDS',
       'SWEETWATER FARM', 'ALTAMAR BRANDS LLC', 'CANDIA VINEYARDS',
       'INCREDIBREW INC', 'ALISA CARR BEVERAGES',
       'STELLAR IMPORTING CO LLC', 'FULCHINO VINEYARD INC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'Circa Wines',
       'VINEDREA WINES LLC', 'BLACK PRINCE DISTILLERY INC',
       'VINEYARD BRANDS LLC', 'THE IMPORTED GRAPE LLC',
       'WALPOLE MTN VIEW WINERY', 'GILMANTON WINERY & VINEYARD',
       'HAUNTING WHISPER VYDS', 'STAR INDUSTRIES INC.',
       'LOYAL DOG WINERY', 'R.P.IMPORTS INC', 'THE PIERPONT GROUP LLC',
       'APPOLO VINEYARDS LLC', 'BLACK ROCK SPIRITS LLC',
       'CENTEUR IMPORTS LLC', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE', 'UNCORKED', 'BRONCO WINE COMPANY',
       'MILTONS DISTRIBUTING CO', 'TRUETT HURST', 'LAUREATE IMPORTS CO',
       'FANTASY FINE WINES CORP', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS', 'CAPSTONE INTERNATIONAL',
       'FLAVOR ESSENCE INC'], dtype=object)

In [30]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']

In [31]:
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalSalesDollars'])*100

In [32]:
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']

In [33]:
vendor_sales_summary['StockPurchaseRatio']= vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [34]:
vendor_sales_summary.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'ActualPrice', 'Volume', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'TotalSalesQuantity', 'TotalSalesDollars',
       'TotalSalesPrice', 'TotalExciseTax', 'FreightCost', 'GrossProfit',
       'ProfitMargin', 'StockTurnover', 'StockPurchaseRatio'],
      dtype='object')

In [35]:
cursor = conn.cursor()

In [36]:
cursor.execute("""
DROP TABLE IF EXISTS vendor_sales_summary;
""")
conn.commit()

In [37]:
cursor.execute(""" Create Table vendor_sales_summary (
    VendorNumber INT,
    VendorName varchar(100),
    Brand INT,
    Description VARCHAR(100),
    PurchasePrice Decimal(10,2),
    ActualPrice Decimal(10,2),
    Volume,
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars Decimal(15,2),
    TotalSalesQuantity INT,
    TotalSalesDollars Decimal(15,2),
    TotalSalesPrice Decimal(15,2),
    FreightCost Decimal(15,2),
    GrossProfit Decimal(15,2),
    ProfitMargin Decimal(15,2),
    StockTurnover Decimal(15,2),
    PRIMARY KEY (VendorNumber , Brand)
    );
    """)

In [38]:
pd.read_sql_query("select * from vendor_sales_summary",conn)

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDollars, TotalSalesQuantity, TotalSalesDollars, TotalSalesPrice, FreightCost, GrossProfit, ProfitMargin, StockTurnover]
Index: []

In [39]:
vendor_sales_summary.to_sql('vendor_sales_summary',conn , if_exists = 'replace',index = False)

10692

In [40]:
import  sqlite3
import pandas as pd
import logging
from ingestion_db import ingest_db

logging.basicConfig(
    filename="logs/get_vendor_summary.log",
    level=logging.DEBUG,
    format = "%(asctime)s - %(levelname)s - %(message)s",
    filemode = "a"
)

   
def create_vendor_summary(conn):
    ''' this function will merge the different tables to get the overall vendor summary and adding new colums in the resultant data'''
    vendor_sales_summary = pd.read_sql_query("""WITH FreightSummary As(
    Select
        VendorNumber,
        SUM(Freight) AS FreightCost
    From vendor_invoice
    Group by VendorNumber
    ),
    
    PurchaseSummary AS (
       SELECT 
           P.VendorNumber, 
           P.VendorName,
           P.Brand,
           P.Description,
           P.PurchasePrice,
           pp.Price As ActualPrice,
           pp.Volume,
           SUM(P.Quantity) AS TotalPurchaseQuantity,
           SUM(P.Dollars) AS TotalPurchaseDollars
       From purchases P
       JOIN purchase_prices pp
            ON P.Brand = pp.Brand
       Where P.PurchasePrice > 0 
       Group BY P.VendorNumber , P.VendorName , P.Brand , P.Description , P.PurchasePrice , pp.Price , pp.Volume),
       
       SalesSummary AS (
        SELECT
           VendorNo,
           Brand,
           SUM(SalesQuantity) AS TotalSalesQuantity,
           SUM(SalesDollars) AS TotalSalesDollars,
           SUM(SalesPrice) AS TotalSalesPrice,
           Sum(ExciseTax) AS TotalExciseTax
        FROM sales
        Group by VendorNo, Brand
        )
    
        SELECT
        ps.VendorNumber,
        ps.VendorName,
        ps.Brand,
        ps.Description,
        ps.PurchasePrice,
        ps.ActualPrice,
        ps.Volume,
        ps.TotalPurchaseQuantity,
        ps.TotalPurchaseDollars,
        ss.TotalSalesQuantity,
        ss.TotalSalesDollars,
        ss.TotalSalesPrice,
        ss.TotalExciseTax,
        fs.FreightCost
    From PurchaseSummary ps
    LEFT JOIN SalesSummary ss
         ON ps.VendorNumber = ss.VendorNo
         AND ps.Brand = ss.Brand
    LEFT JOIN FreightSummary fs
         ON ps.VendorNumber = fs.VendorNumber
    ORDER BY ps.TotalpurchaseDollars DESC """,conn) 
    
    return vendor_sales_summary

def clean_data(df):
    '''this function will clean the data'''
    # changing datatype to float
    df['Volume'] = df['Volume'].astype('float')

    # filling missing value with 0
    df.fillna (0,inplace = True)

    # removing spaces from categorial columns
    df['VendorName'] = df['VendorName'].str.strip()
    df['Description'] = df ['Description'].str.strip()


    #  Creating new columns for better analysis
    # df['GrossProfit'] = df['TotalSalesDollars'] - df['TotalPurchaseDollars']
    # df['ProfitMargin'] = (df['GrossProfit']/df['TotalSalesDollars'])*100
    # df['StockTurnover'] = df['TotalSalesQuantity']/df['TotalPurchaseQuantity']
    # df['StockPurchaseRatio']= df['TotalSalesDollars']/df['TotalPurchaseDollars']

    vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']
    vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalSalesDollars'])*100
    vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']
    vendor_sales_summary['StockPurchaseRatio']= vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

    return df 

if __name__ == "__main__":

    # import os
    # os.makedirs("logs", exist_ok=True)
    
    conn = sqlite3.connect('inventorys.db')
    
    logging.info ('Creating Vendor Summary Table.....')
    summary_df = create_vendor_summary(conn)
    logging.info(summary_df.head())


    logging.info ('Cleaning Data.....')
    clean_df = clean_data(summary_df)
    logging.info(clean_df.head())

    logging.info('Ingesting data....')
    ingest_db(clean_df,'vendor_sales_summary',conn)
    logging.info('Completed')

    # Read the table into a DataFrame
df = pd.read_sql_query("SELECT * FROM vendor_sales_summary", conn)

print(df.head())   # display first 5 rows

   VendorNumber                VendorName  Brand              Description  \
0          1128         BROWN-FORMAN CORP   1233  Jack Daniels No 7 Black
1          4425     MARTIGNETTI COMPANIES   3405    Tito's Handmade Vodka
2         17035         PERNOD RICARD USA   8068         Absolut 80 Proof
3          3960  DIAGEO NORTH AMERICA INC   4261   Capt Morgan Spiced Rum
4          3960  DIAGEO NORTH AMERICA INC   3545          Ketel One Vodka

   PurchasePrice  ActualPrice  Volume  TotalPurchaseQuantity  \
0          26.27        36.99  1750.0                 145080
1          23.19        28.99  1750.0                 164038
2          18.24        24.99  1750.0                 187407
3          16.17        22.99  1750.0                 201682
4          21.89        29.99  1750.0                 138109

   TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  \
0            3811251.60            142049.0         5101919.51
1            3804041.22            160247.0         4819073.49
2            3418303.68            187140.0         4538120.60
3            3261197.94            200412.0         4475972.88
4            3023206.01            135838.0         4223107.62

   TotalSalesPrice  TotalExciseTax  FreightCost  GrossProfit  ProfitMargin  \
0        672819.31       260999.20     68601.68   1290667.91     25.297693
1        561512.37       294438.66    144929.24   1015032.27     21.062810
2        461140.15       343854.07    123780.22   1119816.92     24.675786
3        420050.01       368242.80    257032.07   1214774.94     27.139908
4        545778.28       249587.83    257032.07   1199901.61     28.412764

   StockTurnover  StockPurchaseRatio
0       0.979108            1.338647
1       0.976890            1.266830
2       0.998575            1.327594
3       0.993703            1.372493
4       0.983556            1.396897

In [42]:
vendor_sales_summary.to_csv("vendor_sales_summary.csv", index=False)

In [43]:
# import sqlite3
# import pandas as pd

# conn = sqlite3.connect("inventorys.db")

# tables = [
#     "begin_inventory",
#     "end_inventory",
#     "purchases",
#     "purchase_prices",
#     "sales",
#     "vendor_invoice",
#     "vendor_sales_summary"
# ]

# def clean_table(df, table_name):
#     # Fill missing values
#     df.fillna(0, inplace=True)

#     # Strip spaces from string columns
#     for col in df.select_dtypes(include="object").columns:
#         df[col] = df[col].str.strip()

#     # Convert numeric columns to float where possible
#     for col in df.select_dtypes(include="number").columns:
#         df[col] = df[col].astype(float)

#     print(f" Cleaned {table_name}")
#     return df

# # Export each table after cleaning
# for table in tables:
#     df = pd.read_sql_query(f"SELECT * FROM {table}", conn)
#     df = clean_table(df, table)
#     df.to_csv(f"{table}.csv", index=False)
#     print(f"Exported {table} to {table}.csv")

# conn.close()

In [47]:
print(df.describe())

        VendorNumber         Brand  PurchasePrice   ActualPrice        Volume  \
count   21384.000000  21384.000000   21384.000000  21384.000000  21384.000000
mean    10650.649458  18039.228769      24.385303     35.643671    847.360550
std     18753.080628  12661.890990     109.266819    148.242550    664.293678
min         2.000000     58.000000       0.360000      0.490000     50.000000
25%      3951.000000   5793.500000       6.840000     10.990000    750.000000
50%      7153.000000  18761.500000      10.455000     15.990000    750.000000
75%      9552.000000  25514.250000      19.482500     28.990000    750.000000
max    201359.000000  90631.000000    5681.810000   7499.990000  20000.000000

       TotalPurchaseQuantity  TotalPurchaseDollars  TotalSalesQuantity  \
count           21384.000000          2.138400e+04        21384.000000
mean             3140.886831          3.010669e+04         3077.482136
std             11094.827329          1.230649e+05        10952.595277
min                 1.000000          7.100000e-01            0.000000
25%                36.000000          4.534575e+02           33.000000
50%               262.000000          3.655465e+03          261.000000
75%              1975.750000          2.073825e+04         1929.250000
max            337660.000000          3.811252e+06       334939.000000

       TotalSalesDollars  TotalSalesPrice  TotalExciseTax    FreightCost  \
count       2.138400e+04     21384.000000    21384.000000   21384.000000
mean        4.223907e+04     18793.783627     1774.226259   61433.763214
std         1.676513e+05     44951.722240    10975.325594   60937.033088
min         0.000000e+00         0.000000        0.000000       0.090000
25%         7.292200e+02       289.710000        4.800000   14069.870000
50%         5.298045e+03      2857.800000       46.570000   50293.620000
75%         2.839692e+04     16059.562500      418.650000   79528.990000
max         5.101920e+06    672819.310000   368242.800000  257032.070000

        GrossProfit  ProfitMargin  StockTurnover  StockPurchaseRatio
count  1.069200e+04  1.069200e+04   10692.000000        10692.000000
mean   1.213238e+04          -inf       1.706793            2.504390
std    4.622434e+04           NaN       6.020460            8.459067
min   -5.200278e+04          -inf       0.000000            0.000000
25%    5.292000e+01  1.332451e+01       0.807229            1.153729
50%    1.399640e+03  3.040546e+01       0.981529            1.436894
75%    8.660200e+03  3.995613e+01       1.039342            1.665449
max    1.290668e+06  9.971666e+01     274.500000          352.928571

In [65]:
summary = df.describe()

# Option 1: Print directly (basic table)
print(summary)

# Option 2: Format nicely for Jupyter Notebook / report
summary.style.set_table_styles(
    [{'selector': 'th', 'props': [('font-size', '12pt'), ('text-align', 'center')]},
     {'selector': 'td', 'props': [('font-size', '11pt')]}]
).set_caption("Exploratory Data Analysis Insights - Summary Statistics")

# summary.style.set_table_styles(
#     [{'selector': 'td', 'props': [('font-size', '10pt'), ('text-align', 'center')]},
#      {'selector': 'th', 'props': [('font-size', '11pt'),]}]
# ).set_caption("Exploratory Data Analysis Insights - Summary Statistics")

        VendorNumber         Brand  PurchasePrice   ActualPrice        Volume  \
count   21384.000000  21384.000000   21384.000000  21384.000000  21384.000000
mean    10650.649458  18039.228769      24.385303     35.643671    847.360550
std     18753.080628  12661.890990     109.266819    148.242550    664.293678
min         2.000000     58.000000       0.360000      0.490000     50.000000
25%      3951.000000   5793.500000       6.840000     10.990000    750.000000
50%      7153.000000  18761.500000      10.455000     15.990000    750.000000
75%      9552.000000  25514.250000      19.482500     28.990000    750.000000
max    201359.000000  90631.000000    5681.810000   7499.990000  20000.000000

       TotalPurchaseQuantity  TotalPurchaseDollars  TotalSalesQuantity  \
count           21384.000000          2.138400e+04        21384.000000
mean             3140.886831          3.010669e+04         3077.482136
std             11094.827329          1.230649e+05        10952.595277
min                 1.000000          7.100000e-01            0.000000
25%                36.000000          4.534575e+02           33.000000
50%               262.000000          3.655465e+03          261.000000
75%              1975.750000          2.073825e+04         1929.250000
max            337660.000000          3.811252e+06       334939.000000

       TotalSalesDollars  TotalSalesPrice  TotalExciseTax    FreightCost  \
count       2.138400e+04     21384.000000    21384.000000   21384.000000
mean        4.223907e+04     18793.783627     1774.226259   61433.763214
std         1.676513e+05     44951.722240    10975.325594   60937.033088
min         0.000000e+00         0.000000        0.000000       0.090000
25%         7.292200e+02       289.710000        4.800000   14069.870000
50%         5.298045e+03      2857.800000       46.570000   50293.620000
75%         2.839692e+04     16059.562500      418.650000   79528.990000
max         5.101920e+06    672819.310000   368242.800000  257032.070000

        GrossProfit  ProfitMargin  StockTurnover  StockPurchaseRatio
count  1.069200e+04  1.069200e+04   10692.000000        10692.000000
mean   1.213238e+04          -inf       1.706793            2.504390
std    4.622434e+04           NaN       6.020460            8.459067
min   -5.200278e+04          -inf       0.000000            0.000000
25%    5.292000e+01  1.332451e+01       0.807229            1.153729
50%    1.399640e+03  3.040546e+01       0.981529            1.436894
75%    8.660200e+03  3.995613e+01       1.039342            1.665449
max    1.290668e+06  9.971666e+01     274.500000          352.928571

In [44]:
begin_inventory.to_csv("begin_inventory.csv", index=False)
end_inventory.to_csv("end_inventory.csv", index=False)
purchases.to_csv("purchases.csv", index=False)
purchase_prices.to_csv("purchase_prices.csv", index=False)
sales.to_csv("sales.csv", index=False)
vendor_invoice.to_csv("vendor_invoice.csv", index=False)

NameError: name 'begin_inventory' is not defined

In [ ]:
vendor_invoice.to_csv("vendor_invoice.csv", index=False)